// rdp_credentials.js
module.exports = [
    // User-provided credentials
    { "username": "Administrator", "password": "Password123" },
    { "username": "admin", "password": "password" },
    { "username": "user", "password": "user" },
    { "username": "Administrator", "password": "" },
    { "username": "admin", "password": "123456" },
    { "username": "test", "password": "test" },
    { "username": "guest", "password": "guest" },
    { "username": "root", "password": "toor" },
    { "username": "user", "password": "12345" },
    { "username": "admin", "password": "admin" },
    { "username": "support", "password": "support" },
    { "username": "operator", "password": "operator" },
    { "username": "guest", "password": "" },
    { "username": "user", "password": "password1" },
    { "username": "admin", "password": "admin123" },
    { "username": "remote", "password": "remote" },
    { "username": "rdpuser", "password": "rdppass" },
    { "username": "default", "password": "default" },
    { "username": "user", "password": "changeme" },
    { "username": "admin", "password": "changeme" },

    // Additional common RDP credentials
    { "username": "Administrator", "password": "admin" },
    { "username": "admin", "password": "password123" },
    { "username": "user", "password": "password" },
    { "username": "Administrator", "password": "123456" },
    { "username": "admin", "password": "" },
    { "username": "user", "password": "" },
    { "username": "Administrator", "password": "P@ssw0rd" },
    { "username": "admin", "password": "Admin123" },
    { "username": "user", "password": "User123" },
    { "username": "Administrator", "password": "Password" },
    { "username": "admin", "password": "Admin" },
    { "username": "user", "password": "Password" },
    { "username": "Administrator", "password": "12345" },
    { "username": "admin", "password": "1234" },
    { "username": "user", "password": "1234" },
    { "username": "Administrator", "password": "Welcome1" },
    { "username": "admin", "password": "Welcome1" },
    { "username": "user", "password": "Welcome1" },
    { "username": "Administrator", "password": "ChangeMe" },
    { "username": "admin", "password": "ChangeMe" }
];